name: Deploy to FTP

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checa el repositorio en la máquina de GitHub Actions
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configura el entorno para la carga por FTP
    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 217.76.156.104  # Reemplaza con tu servidor FTP
        username: ${{ secrets.FTP_USERNAME }} # Usa un secreto para el usuario
        password: ${{ secrets.FTP_PASSWORD }} # Usa un secreto para la contraseña
        local-dir: ./public                # Carpeta local que quieres subir
        server-dir: /html/prueba # Carpeta destino en el servidor
