name: Deploy to SFTP

on:
  push:
    branches:
      - dev  # Esto activará el deploy solo cuando hagas un push en la rama "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usamos un entorno Ubuntu para ejecutar el job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Clona el repositorio

    - name: Deploy to SFTP
      uses: appleboy/ssh-action@v0.1.8  # Acción para usar SFTP
      with:
        host: ${{ secrets.SFTP_HOST }}  # Dirección del servidor
        username: ${{ secrets.SFTP_USER }}  # Usuario para autenticación
        password: ${{ secrets.SFTP_PASSWORD }}  # Contraseña del usuario (si usas contraseña)
        port: 22  # Puerto SFTP (por defecto es 22)
        source: "./public/*"  # Carpeta local que quieres subir
        target: "/html/prueba/"  # Carpeta destino en el servidor
        strip_components: 1  # Si la carpeta 'public' es la raíz del contenido a subir
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}  # Usa la clave privada SSH si no usas contraseña
