name: Deploy to SFTP

on:
  push:
    branches:
      - dev  # Esto activará el deploy solo cuando hagas un push en la rama "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usamos un entorno Ubuntu para ejecutar el job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Clona el repositorio

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Usamos una variable de entorno para la clave SSH privada

    - name: Deploy to SFTP
      run: |
        # Usamos lftp para conectarnos al servidor SFTP y hacer el upload
        sudo apt-get install lftp -y  # Instalamos lftp, necesario para la conexión SFTP

        # Comando lftp para sincronizar la carpeta 'public' con el servidor SFTP
        lftp -f "
          open -u ${{ secrets.SFTP_USER }},$${{ secrets.SFTP_PASSWORD }} sftp://$${{ secrets.SFTP_HOST }}
          mirror -R ./public /html/prueba
          quit
        "
