name: Deploy to SFTP

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to SFTP
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        source: "./public/"
        target: "./html/prueba/"
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true  # Activa la opción de debug
