name: Deploy to SFTP

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload files using SFTP
      uses: appleboy/sftp-action@v0.1.0
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        source: "./public/*"
        target: "/var/www/html/prueba/"

